// Generated by CoffeeScript 1.7.1
(function() {
  var app, bodyParser, express, logger, router, xiki;

  express = require('express');

  logger = require('morgan');

  bodyParser = require('body-parser');

  xiki = require('xiki');

  app = express();

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded());

  app.use(bodyParser.text());

  router = express.Router();

  router.get("*", xiki);

  app.use('/', router);

  app.set("view engine", "jade");

  app.use(function(req, res, next) {
    var err;
    err = new Error("Not Found");
    err.status = 404;
    return next(err);
  });

  if (app.get('env') === "development") {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);
