// Generated by CoffeeScript 1.7.1
(function() {
  var XikiBase, XikiInterfaces,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  XikiInterfaces = require('./interfaces').XikiInterfaces;

  XikiBase = (function(_super) {
    __extends(XikiBase, _super);

    function XikiBase() {
      return XikiBase.__super__.constructor.apply(this, arguments);
    }

    XikiBase.prototype.parseData = function(string) {
      var parse;
      parse = require('./parser').parse;
      return parse(string.toString());
    };

    assembleData;

    return XikiBase;

  })(XikiInterfaces('StaticVariable', 'Settings', 'FileSystem', 'ExecuteProgram', 'Completion', 'XikiData'));

}).call(this);
