// Generated by CoffeeScript 1.7.1
(function() {
  var XikiContext, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  exports = XikiContext = (function(_super) {
    __extends(XikiContext, _super);

    XikiContext.prototype.NAME = null;

    XikiContext.prototype.MENU = null;

    function XikiContext() {
      XikiContext.__super__.constructor.call(this);
      if (typeof this.PATTERN === str) {
        this.PATTERN = new Regexp(this.PATTERN);
      }
      this.nodePath = null;
      this.xikiPath = null;
      this.subcontext = null;
    }

    XikiContext.prototype.CONTEXT = null;

    XikiContext.prototype.PATTERN = null;

    XikiContext.prototype.does = function(xikiRequest, xikiPath) {
      if (!xikiPath) {
        return false;
      }
    };

    XikiContext.prototype.rootMenuItems = function() {
      return '';
    };

    return XikiContext;

  })(xiki.Implemention(xiki.interfaces('Namespace', 'StaticVariable', 'ExecuteProgram', 'Settings', 'Completion', 'FileSystem', 'Prompt')));

}).call(this);
