// Generated by CoffeeScript 1.7.1
(function() {
  var Interface;

  Interface = (function() {
    function Interface() {
      this._registry = {};
      this._defaults = {};
    }

    Interface.prototype.define = function(cls) {
      var name;
      name = cls.constructor.name;
      console.log(cls);
      console.log(name);
      console.log("" + name);
      return this[name] = this._registry[name] = cls;
    };

    Interface.prototype["default"] = function(cls) {
      console.log("default", cls);
      return this._defaults[cls.constructor.name] = cls;
    };

    Interface.prototype.mixDefaultsInto = function(target) {
      var method, mixin, name, _i, _len, _ref, _ref1;
      _ref = this._defaults;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mixin = _ref[_i];
        _ref1 = mixin.prototype;
        for (name in _ref1) {
          method = _ref1[name];
          target.prototype[name] = method;
        }
      }
      return target;
    };

    return Interface;

  })();

  module.exports = new Interface();

}).call(this);
